# Generated by Django 4.1.3 on 2022-11-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
