# Generated by Django 4.1.2 on 2022-11-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_1',
            field=models.ImageField(null=True, upload_to='OrderImages/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='OrderImages/'),
        ),
        migrations.AddField(
            model_name='order',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='OrderImages/'),
        ),
        migrations.DeleteModel(
            name='OrderImages',
        ),
    ]
